import { migration } from 'nesoi/lib/adapters/postgres/src/migrator';

/**
 * $migration[1746142713542_cameras]
 *
 * $type[create]
 * $table[cameras]
 *
 * Migration auto-generated by @nesoi/postgres. Don't modify it manually.
 */

export default migration({
	hash: '946261e4a835020bea1b173500fc59d9',
	description: '',
	up: async ({ sql }) => {
		await sql`
			CREATE TABLE cameras (
				"id" serial4 PRIMARY KEY  NOT NULL,
				"state" character varying  NOT NULL,
				"alias" character varying  NOT NULL,
				"hash" character varying  NOT NULL,
				"stream_id" character varying  NOT NULL,
				"harbor_id" integer  NOT NULL,
				"coord_x" double precision  NOT NULL,
				"coord_y" double precision  NOT NULL,
				"coord_z" double precision  NOT NULL,
				"rot_x" double precision  NOT NULL,
				"rot_y" double precision  NOT NULL,
				"rot_z" double precision  NOT NULL,
				"type_id" integer  NOT NULL,
				"sensor_width" double precision  NOT NULL,
				"sensor_height" double precision  NOT NULL,
				"created_by" character(64) ,
				"created_at" timestamp without time zone  NOT NULL,
				"updated_by" character(64) ,
				"updated_at" timestamp without time zone  NOT NULL
			)
		`
	},
	down: async ({ sql }) => {
		await sql`
			DROP TABLE cameras
		`
	}
})